import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# Script generated for node S3 bucket
S3bucket_node1 = glueContext.create_dynamic_frame.from_options(
    format_options={"quoteChar": '"', "withHeader": True, "separator": ","},
    connection_type="s3",
    format="csv",
    connection_options={
        "paths": ["s3://staging-bucket-orka-data/matches.csv"],
        "recurse": True,
    },
    transformation_ctx="S3bucket_node1",
)

# Script generated for node Amazon S3
AmazonS3_node1684640736068 = glueContext.create_dynamic_frame.from_options(
    format_options={"quoteChar": '"', "withHeader": True, "separator": ","},
    connection_type="s3",
    format="csv",
    connection_options={
        "paths": ["s3://staging-bucket-orka-data/players.csv"],
        "recurse": True,
    },
    transformation_ctx="AmazonS3_node1684640736068",
)

# Script generated for node Amazon S3
AmazonS3_node1684640892050 = glueContext.create_dynamic_frame.from_options(
    format_options={"quoteChar": '"', "withHeader": True, "separator": ","},
    connection_type="s3",
    format="csv",
    connection_options={
        "paths": ["s3://staging-bucket-orka-data/delivery.csv"],
        "recurse": True,
    },
    transformation_ctx="AmazonS3_node1684640892050",
)

# Script generated for node ApplyMapping
ApplyMapping_node2 = ApplyMapping.apply(
    frame=S3bucket_node1,
    mappings=[
        ("id", "string", "id", "string"),
        ("Season", "string", "Season", "string"),
        ("city", "string", "city", "string"),
        ("date", "string", "date", "string"),
        ("team1", "string", "team1", "string"),
        ("team2", "string", "team2", "string"),
        ("toss_winner", "string", "toss_winner", "string"),
        ("toss_decision", "string", "toss_decision", "string"),
        ("result", "string", "result", "string"),
        ("dl_applied", "string", "dl_applied", "string"),
        ("winner", "string", "winner", "string"),
        ("win_by_runs", "string", "win_by_runs", "string"),
        ("win_by_wickets", "string", "win_by_wickets", "string"),
        ("player_of_match", "string", "player_of_match", "string"),
        ("venue", "string", "venue", "string"),
        ("umpire1", "string", "umpire1", "string"),
        ("umpire2", "string", "umpire2", "string"),
        ("umpire3", "string", "umpire3", "string"),
    ],
    transformation_ctx="ApplyMapping_node2",
)

# Script generated for node Change Schema
ChangeSchema_node1684640761053 = ApplyMapping.apply(
    frame=AmazonS3_node1684640736068,
    mappings=[
        ("Unnamed: 0", "string", "Unnamed: 0", "string"),
        ("ID", "string", "ID", "string"),
        ("NAME", "string", "NAME", "string"),
        ("COUNTRY", "string", "COUNTRY", "string"),
        ("Full name", "string", "Full name", "string"),
        ("Birthdate", "string", "Birthdate", "string"),
        ("Birthplace", "string", "Birthplace", "string"),
        ("Died", "string", "Died", "string"),
        ("Date_of_death", "string", "Date_of_death", "string"),
        ("Age", "string", "Age", "string"),
        ("Major teams", "string", "Major teams", "string"),
        ("Batting style", "string", "Batting style", "string"),
        ("Bowling style", "string", "Bowling style", "string"),
        ("Other", "string", "Other", "string"),
        ("AWARDS", "string", "AWARDS", "string"),
        ("BATTING_Tests_Mat", "string", "BATTING_Tests_Mat", "string"),
        ("BATTING_Tests_Inns", "string", "BATTING_Tests_Inns", "string"),
        ("BATTING_Tests_NO", "string", "BATTING_Tests_NO", "string"),
        ("BATTING_Tests_Runs", "string", "BATTING_Tests_Runs", "string"),
        ("BATTING_Tests_HS", "string", "BATTING_Tests_HS", "string"),
        ("BATTING_Tests_Ave", "string", "BATTING_Tests_Ave", "string"),
        ("BATTING_Tests_BF", "string", "BATTING_Tests_BF", "string"),
        ("BATTING_Tests_SR", "string", "BATTING_Tests_SR", "string"),
        ("BATTING_Tests_100", "string", "BATTING_Tests_100", "string"),
        ("BATTING_Tests_50", "string", "BATTING_Tests_50", "string"),
        ("BATTING_Tests_4s", "string", "BATTING_Tests_4s", "string"),
        ("BATTING_Tests_6s", "string", "BATTING_Tests_6s", "string"),
        ("BATTING_Tests_Ct", "string", "BATTING_Tests_Ct", "string"),
        ("BATTING_Tests_St", "string", "BATTING_Tests_St", "string"),
        ("BATTING_ODIs_Mat", "string", "BATTING_ODIs_Mat", "string"),
        ("BATTING_ODIs_Inns", "string", "BATTING_ODIs_Inns", "string"),
        ("BATTING_ODIs_NO", "string", "BATTING_ODIs_NO", "string"),
        ("BATTING_ODIs_Runs", "string", "BATTING_ODIs_Runs", "string"),
        ("BATTING_ODIs_HS", "string", "BATTING_ODIs_HS", "string"),
        ("BATTING_ODIs_Ave", "string", "BATTING_ODIs_Ave", "string"),
        ("BATTING_ODIs_BF", "string", "BATTING_ODIs_BF", "string"),
        ("BATTING_ODIs_SR", "string", "BATTING_ODIs_SR", "string"),
        ("BATTING_ODIs_100", "string", "BATTING_ODIs_100", "string"),
        ("BATTING_ODIs_50", "string", "BATTING_ODIs_50", "string"),
        ("BATTING_ODIs_4s", "string", "BATTING_ODIs_4s", "string"),
        ("BATTING_ODIs_6s", "string", "BATTING_ODIs_6s", "string"),
        ("BATTING_ODIs_Ct", "string", "BATTING_ODIs_Ct", "string"),
        ("BATTING_ODIs_St", "string", "BATTING_ODIs_St", "string"),
        ("BATTING_T20Is_Mat", "string", "BATTING_T20Is_Mat", "string"),
        ("BATTING_T20Is_Inns", "string", "BATTING_T20Is_Inns", "string"),
        ("BATTING_T20Is_NO", "string", "BATTING_T20Is_NO", "string"),
        ("BATTING_T20Is_Runs", "string", "BATTING_T20Is_Runs", "string"),
        ("BATTING_T20Is_HS", "string", "BATTING_T20Is_HS", "string"),
        ("BATTING_T20Is_Ave", "string", "BATTING_T20Is_Ave", "string"),
        ("BATTING_T20Is_BF", "string", "BATTING_T20Is_BF", "string"),
        ("BATTING_T20Is_SR", "string", "BATTING_T20Is_SR", "string"),
        ("BATTING_T20Is_100", "string", "BATTING_T20Is_100", "string"),
        ("BATTING_T20Is_50", "string", "BATTING_T20Is_50", "string"),
        ("BATTING_T20Is_4s", "string", "BATTING_T20Is_4s", "string"),
        ("BATTING_T20Is_6s", "string", "BATTING_T20Is_6s", "string"),
        ("BATTING_T20Is_Ct", "string", "BATTING_T20Is_Ct", "string"),
        ("BATTING_T20Is_St", "string", "BATTING_T20Is_St", "string"),
        ("BATTING_First-class_Mat", "string", "BATTING_First-class_Mat", "string"),
        ("BATTING_First-class_Inns", "string", "BATTING_First-class_Inns", "string"),
        ("BATTING_First-class_NO", "string", "BATTING_First-class_NO", "string"),
        ("BATTING_First-class_Runs", "string", "BATTING_First-class_Runs", "string"),
        ("BATTING_First-class_HS", "string", "BATTING_First-class_HS", "string"),
        ("BATTING_First-class_Ave", "string", "BATTING_First-class_Ave", "string"),
        ("BATTING_First-class_BF", "string", "BATTING_First-class_BF", "string"),
        ("BATTING_First-class_SR", "string", "BATTING_First-class_SR", "string"),
        ("BATTING_First-class_100", "string", "BATTING_First-class_100", "string"),
        ("BATTING_First-class_50", "string", "BATTING_First-class_50", "string"),
        ("BATTING_First-class_4s", "string", "BATTING_First-class_4s", "string"),
        ("BATTING_First-class_6s", "string", "BATTING_First-class_6s", "string"),
        ("BATTING_First-class_Ct", "string", "BATTING_First-class_Ct", "string"),
        ("BATTING_First-class_St", "string", "BATTING_First-class_St", "string"),
        ("BATTING_List A_Mat", "string", "BATTING_List A_Mat", "string"),
        ("BATTING_List A_Inns", "string", "BATTING_List A_Inns", "string"),
        ("BATTING_List A_NO", "string", "BATTING_List A_NO", "string"),
        ("BATTING_List A_Runs", "string", "BATTING_List A_Runs", "string"),
        ("BATTING_List A_HS", "string", "BATTING_List A_HS", "string"),
        ("BATTING_List A_Ave", "string", "BATTING_List A_Ave", "string"),
        ("BATTING_List A_BF", "string", "BATTING_List A_BF", "string"),
        ("BATTING_List A_SR", "string", "BATTING_List A_SR", "string"),
        ("BATTING_List A_100", "string", "BATTING_List A_100", "string"),
        ("BATTING_List A_50", "string", "BATTING_List A_50", "string"),
        ("BATTING_List A_4s", "string", "BATTING_List A_4s", "string"),
        ("BATTING_List A_6s", "string", "BATTING_List A_6s", "string"),
        ("BATTING_List A_Ct", "string", "BATTING_List A_Ct", "string"),
        ("BATTING_List A_St", "string", "BATTING_List A_St", "string"),
        ("BATTING_T20s_Mat", "string", "BATTING_T20s_Mat", "string"),
        ("BATTING_T20s_Inns", "string", "BATTING_T20s_Inns", "string"),
        ("BATTING_T20s_NO", "string", "BATTING_T20s_NO", "string"),
        ("BATTING_T20s_Runs", "string", "BATTING_T20s_Runs", "string"),
        ("BATTING_T20s_HS", "string", "BATTING_T20s_HS", "string"),
        ("BATTING_T20s_Ave", "string", "BATTING_T20s_Ave", "string"),
        ("BATTING_T20s_BF", "string", "BATTING_T20s_BF", "string"),
        ("BATTING_T20s_SR", "string", "BATTING_T20s_SR", "string"),
        ("BATTING_T20s_100", "string", "BATTING_T20s_100", "string"),
        ("BATTING_T20s_50", "string", "BATTING_T20s_50", "string"),
        ("BATTING_T20s_4s", "string", "BATTING_T20s_4s", "string"),
        ("BATTING_T20s_6s", "string", "BATTING_T20s_6s", "string"),
        ("BATTING_T20s_Ct", "string", "BATTING_T20s_Ct", "string"),
        ("BATTING_T20s_St", "string", "BATTING_T20s_St", "string"),
        ("BOWLING_Tests_Mat", "string", "BOWLING_Tests_Mat", "string"),
        ("BOWLING_Tests_Inns", "string", "BOWLING_Tests_Inns", "string"),
        ("BOWLING_Tests_Balls", "string", "BOWLING_Tests_Balls", "string"),
        ("BOWLING_Tests_Runs", "string", "BOWLING_Tests_Runs", "string"),
        ("BOWLING_Tests_Wkts", "string", "BOWLING_Tests_Wkts", "string"),
        ("BOWLING_Tests_BBI", "string", "BOWLING_Tests_BBI", "string"),
        ("BOWLING_Tests_BBM", "string", "BOWLING_Tests_BBM", "string"),
        ("BOWLING_Tests_Ave", "string", "BOWLING_Tests_Ave", "string"),
        ("BOWLING_Tests_Econ", "string", "BOWLING_Tests_Econ", "string"),
        ("BOWLING_Tests_SR", "string", "BOWLING_Tests_SR", "string"),
        ("BOWLING_Tests_4w", "string", "BOWLING_Tests_4w", "string"),
        ("BOWLING_Tests_5w", "string", "BOWLING_Tests_5w", "string"),
        ("BOWLING_Tests_10", "string", "BOWLING_Tests_10", "string"),
        ("BOWLING_ODIs_Mat", "string", "BOWLING_ODIs_Mat", "string"),
        ("BOWLING_ODIs_Inns", "string", "BOWLING_ODIs_Inns", "string"),
        ("BOWLING_ODIs_Balls", "string", "BOWLING_ODIs_Balls", "string"),
        ("BOWLING_ODIs_Runs", "string", "BOWLING_ODIs_Runs", "string"),
        ("BOWLING_ODIs_Wkts", "string", "BOWLING_ODIs_Wkts", "string"),
        ("BOWLING_ODIs_BBI", "string", "BOWLING_ODIs_BBI", "string"),
        ("BOWLING_ODIs_BBM", "string", "BOWLING_ODIs_BBM", "string"),
        ("BOWLING_ODIs_Ave", "string", "BOWLING_ODIs_Ave", "string"),
        ("BOWLING_ODIs_Econ", "string", "BOWLING_ODIs_Econ", "string"),
        ("BOWLING_ODIs_SR", "string", "BOWLING_ODIs_SR", "string"),
        ("BOWLING_ODIs_4w", "string", "BOWLING_ODIs_4w", "string"),
        ("BOWLING_ODIs_5w", "string", "BOWLING_ODIs_5w", "string"),
        ("BOWLING_ODIs_10", "string", "BOWLING_ODIs_10", "string"),
        ("BOWLING_T20Is_Mat", "string", "BOWLING_T20Is_Mat", "string"),
        ("BOWLING_T20Is_Inns", "string", "BOWLING_T20Is_Inns", "string"),
        ("BOWLING_T20Is_Balls", "string", "BOWLING_T20Is_Balls", "string"),
        ("BOWLING_T20Is_Runs", "string", "BOWLING_T20Is_Runs", "string"),
        ("BOWLING_T20Is_Wkts", "string", "BOWLING_T20Is_Wkts", "string"),
        ("BOWLING_T20Is_BBI", "string", "BOWLING_T20Is_BBI", "string"),
        ("BOWLING_T20Is_BBM", "string", "BOWLING_T20Is_BBM", "string"),
        ("BOWLING_T20Is_Ave", "string", "BOWLING_T20Is_Ave", "string"),
        ("BOWLING_T20Is_Econ", "string", "BOWLING_T20Is_Econ", "string"),
        ("BOWLING_T20Is_SR", "string", "BOWLING_T20Is_SR", "string"),
        ("BOWLING_T20Is_4w", "string", "BOWLING_T20Is_4w", "string"),
        ("BOWLING_T20Is_5w", "string", "BOWLING_T20Is_5w", "string"),
        ("BOWLING_T20Is_10", "string", "BOWLING_T20Is_10", "string"),
        ("BOWLING_First-class_Mat", "string", "BOWLING_First-class_Mat", "string"),
        ("BOWLING_First-class_Inns", "string", "BOWLING_First-class_Inns", "string"),
        ("BOWLING_First-class_Balls", "string", "BOWLING_First-class_Balls", "string"),
        ("BOWLING_First-class_Runs", "string", "BOWLING_First-class_Runs", "string"),
        ("BOWLING_First-class_Wkts", "string", "BOWLING_First-class_Wkts", "string"),
        ("BOWLING_First-class_BBI", "string", "BOWLING_First-class_BBI", "string"),
        ("BOWLING_First-class_BBM", "string", "BOWLING_First-class_BBM", "string"),
        ("BOWLING_First-class_Ave", "string", "BOWLING_First-class_Ave", "string"),
        ("BOWLING_First-class_Econ", "string", "BOWLING_First-class_Econ", "string"),
        ("BOWLING_First-class_SR", "string", "BOWLING_First-class_SR", "string"),
        ("BOWLING_First-class_4w", "string", "BOWLING_First-class_4w", "string"),
        ("BOWLING_First-class_5w", "string", "BOWLING_First-class_5w", "string"),
        ("BOWLING_First-class_10", "string", "BOWLING_First-class_10", "string"),
        ("BOWLING_List A_Mat", "string", "BOWLING_List A_Mat", "string"),
        ("BOWLING_List A_Inns", "string", "BOWLING_List A_Inns", "string"),
        ("BOWLING_List A_Balls", "string", "BOWLING_List A_Balls", "string"),
        ("BOWLING_List A_Runs", "string", "BOWLING_List A_Runs", "string"),
        ("BOWLING_List A_Wkts", "string", "BOWLING_List A_Wkts", "string"),
        ("BOWLING_List A_BBI", "string", "BOWLING_List A_BBI", "string"),
        ("BOWLING_List A_BBM", "string", "BOWLING_List A_BBM", "string"),
        ("BOWLING_List A_Ave", "string", "BOWLING_List A_Ave", "string"),
        ("BOWLING_List A_Econ", "string", "BOWLING_List A_Econ", "string"),
        ("BOWLING_List A_SR", "string", "BOWLING_List A_SR", "string"),
        ("BOWLING_List A_4w", "string", "BOWLING_List A_4w", "string"),
        ("BOWLING_List A_5w", "string", "BOWLING_List A_5w", "string"),
        ("BOWLING_List A_10", "string", "BOWLING_List A_10", "string"),
        ("BOWLING_T20s_Mat", "string", "BOWLING_T20s_Mat", "string"),
        ("BOWLING_T20s_Inns", "string", "BOWLING_T20s_Inns", "string"),
        ("BOWLING_T20s_Balls", "string", "BOWLING_T20s_Balls", "string"),
        ("BOWLING_T20s_Runs", "string", "BOWLING_T20s_Runs", "string"),
        ("BOWLING_T20s_Wkts", "string", "BOWLING_T20s_Wkts", "string"),
        ("BOWLING_T20s_BBI", "string", "BOWLING_T20s_BBI", "string"),
        ("BOWLING_T20s_BBM", "string", "BOWLING_T20s_BBM", "string"),
        ("BOWLING_T20s_Ave", "string", "BOWLING_T20s_Ave", "string"),
        ("BOWLING_T20s_Econ", "string", "BOWLING_T20s_Econ", "string"),
        ("BOWLING_T20s_SR", "string", "BOWLING_T20s_SR", "string"),
        ("BOWLING_T20s_4w", "string", "BOWLING_T20s_4w", "string"),
        ("BOWLING_T20s_5w", "string", "BOWLING_T20s_5w", "string"),
        ("BOWLING_T20s_10", "string", "BOWLING_T20s_10", "string"),
    ],
    transformation_ctx="ChangeSchema_node1684640761053",
)

# Script generated for node Change Schema
ChangeSchema_node1684640924377 = ApplyMapping.apply(
    frame=AmazonS3_node1684640892050,
    mappings=[
        ("match_id", "string", "match_id", "string"),
        ("inning", "string", "inning", "string"),
        ("batting_team", "string", "batting_team", "string"),
        ("bowling_team", "string", "bowling_team", "string"),
        ("over", "string", "over", "string"),
        ("ball", "string", "ball", "string"),
        ("batsman", "string", "batsman", "string"),
        ("non_striker", "string", "non_striker", "string"),
        ("bowler", "string", "bowler", "string"),
        ("is_super_over", "string", "is_super_over", "string"),
        ("wide_runs", "string", "wide_runs", "string"),
        ("bye_runs", "string", "bye_runs", "string"),
        ("legbye_runs", "string", "legbye_runs", "string"),
        ("noball_runs", "string", "noball_runs", "string"),
        ("penalty_runs", "string", "penalty_runs", "string"),
        ("batsman_runs", "string", "batsman_runs", "string"),
        ("extra_runs", "string", "extra_runs", "string"),
        ("total_runs", "string", "total_runs", "string"),
        ("player_dismissed", "string", "player_dismissed", "string"),
        ("dismissal_kind", "string", "dismissal_kind", "string"),
        ("fielder", "string", "fielder", "string"),
    ],
    transformation_ctx="ChangeSchema_node1684640924377",
)

# Script generated for node PostgreSQL table
PostgreSQLtable_node3 = glueContext.write_dynamic_frame.from_catalog(
    frame=ApplyMapping_node2,
    database="orkadatabase",
    table_name="matches_csv",
    transformation_ctx="PostgreSQLtable_node3",
)

# Script generated for node PostgreSQL
PostgreSQL_node1684640797503 = glueContext.write_dynamic_frame.from_catalog(
    frame=ChangeSchema_node1684640761053,
    database="orkadatabase",
    table_name="players_csv",
    transformation_ctx="PostgreSQL_node1684640797503",
)

# Script generated for node PostgreSQL
PostgreSQL_node1684640936139 = glueContext.write_dynamic_frame.from_catalog(
    frame=ChangeSchema_node1684640924377,
    database="orkadatabase",
    table_name="delivery_csv",
    transformation_ctx="PostgreSQL_node1684640936139",
)

job.commit()
